In [1]:
from custom_envs.dm_control_suite import get_default_config, load
import jax
import jax.numpy as jnp
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "4"


In [9]:
env_name='CheetahRun'
cfg = get_default_config(env_name)
env = load(env_name, cfg)

In [3]:
state = env.reset(jax.random.PRNGKey(0))

In [4]:
env._get_obs(state.data, state.info)

{'state': Array([-0.02442456, -0.9999161 , -0.01295611, -0.02442456, -0.0203568 ],      dtype=float32),
 'privileged_state': Array([-0.02442456, -0.9999161 , -0.01295611, -0.02442456, -0.0203568 ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.5       ,  1.        ,  0.1       ], dtype=float32)}

In [5]:
env.mjx_model.nv

2

In [6]:
for i in range(100):
    action = jnp.ones(1) * 0.01 * (-1)**i
    state = env.step(state, action)

KeyboardInterrupt: 

In [ ]:
env.mjx_model.body_ipos

Array([[0. , 0. , 0. ],
       [0. , 0. , 0. ],
       [0. , 0. , 0.5]], dtype=float32)

In [ ]:
state.data.geom_xpos

Array([[ 0.        ,  0.        , -0.05      ],
       [ 0.        ,  0.07      ,  1.        ],
       [ 0.        , -0.07      ,  1.        ],
       [-0.03722013,  0.        ,  1.        ],
       [-0.03216185,  0.        ,  0.50002563]], dtype=float32)

In [7]:
env.mjx_model.geom_friction

Array([[1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04]], dtype=float32)

In [10]:
env.mjx_model.dof_frictionloss

Array([0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [ ]:
env.mjx_model.